# Generated by Django 4.0 on 2022-01-09 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aadhar_card',
            name='aadhar_card_number',
            field=models.IntegerField(),
        ),
    ]
