# Generated by Django 4.0 on 2022-01-09 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card_details', '0003_alter_aadhar_card_mobile_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aadhar_card',
            old_name='aadhar_card_number',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='pan_card',
            old_name='pan_card_number',
            new_name='number',
        ),
    ]
