# Generated by Django 4.0 on 2022-01-09 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card_details', '0004_rename_aadhar_card_number_aadhar_card_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aadhar_card',
            old_name='number',
            new_name='aadhar_card_number',
        ),
        migrations.RenameField(
            model_name='pan_card',
            old_name='number',
            new_name='pan_card_number',
        ),
    ]
