# Generated by Django 4.0 on 2022-01-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_details', '0007_alter_pan_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pan_card',
            name='number',
            field=models.CharField(max_length=15),
        ),
    ]
